FROM ubuntu:18.04
MAINTAINER showwin <showwin_kmc@yahoo.co.jp>

ENV LANG en_US.UTF-8

RUN apt-get update --fix-missing
RUN apt-get install -y wget sudo less vim tzdata wait-for-it

# ishocon ユーザ作成
RUN groupadd -g 1001 ishocon && \
    useradd  -g ishocon -G sudo -m -s /bin/bash ishocon && \
    echo 'ishocon:ishocon' | chpasswd
RUN echo 'ishocon ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

# MySQL のインストール
RUN ["/bin/bash", "-c", "debconf-set-selections <<< 'mysql-server mysql-server/root_password password ishocon'"]
RUN ["/bin/bash", "-c", "debconf-set-selections <<< 'mysql-service mysql-server/mysql-apt-config string 4'"]
RUN apt-get install -y mysql-client

# Nginx のインストール
RUN apt-get install -y nginx
COPY admin/ssl/ /etc/nginx/ssl/
COPY nginx/nginx.conf /etc/nginx/nginx.conf

# rust/cargo-profilerインストールのために必要なものを入れる
#
RUN apt-get install -y valgrind curl gcc pkg-config libssl-dev linux-tools-common linux-tools-generic linux-tools-generic-hwe-18.04
RUN rm /usr/bin/perf
RUN ln -s /usr/lib/linux-tools/5.4.0-45-generic/perf /usr/bin/perf

USER ishocon

# rust, cargo-profiler入れる
RUN curl https://sh.rustup.rs -sSf | sh -s -- -y
SHELL ["/bin/bash", "-c"]
RUN source /home/ishocon/.cargo/env
ENV PATH $PATH:/home/ishocon/.cargo/bin
COPY webapp/rust/rust-toolchain .
RUN cargo install cargo-profiler
RUN cargo install flamegraph
RUN cargo install cargo-watch

RUN mkdir /home/ishocon/data /home/ishocon/webapp
COPY admin/ishocon2.dump.tar.bz2 /home/ishocon/data/ishocon2.dump.tar.bz2
COPY admin/config/bashrc /home/ishocon/.bashrc


COPY docker/start_app.sh /docker/start_app.sh

WORKDIR /home/ishocon
EXPOSE 443
