#!/bin/bash

set -v

root=$(cd "$(dirname "$0")" && cd .. && pwd)
now=$(date +%Y%m%d-%H%M%S)

branch=${1-master}



command="source ~/.bash_profile; cd /home/isucon/isucari/webapp/go && git remote update && git checkout $branch && git pull && go get && go build -o isucari && sudo systemctl restart isucari.golang"
rotate_nginx="sudo mv /var/log/nginx/access.log /var/log/nginx/access.log.$now && sudo ln -sf /var/log/nginx/access.log.$now /var/log/nginx/access.log.latest; sudo systemctl reload nginx.service"
rotate_mysql="sudo mv /var/log/mysql/slow.log /var/log/mysql/slow.log.$now && sudo ln -sf /var/log/mysql/slow.log.$now /var/log/mysql/slow.log.latest; mysqladmin -uisucon -pisucon flush-logs"

# ssh isucon@isu01 "$command"

ssh isu01 "$rotate_nginx"
# ssh isucon@isu01 "$rotate_mysql"
