#!/bin/bash

set -v

command="cat /var/log/nginx/access.log | alp --matching-groups '/candidates/\d+,/political_parties/.+' --sort=sum --reverse -o count,2xx,method,uri,min,max,sum,avg,p99 ltsv"

ssh isu01 "$command"
